### PR TITLE
Added Huffman Code

### PR DESCRIPTION
**Pull request by SKR301**
A text string can now be encoded using the Huffman Coding Algorithm.

### CODE REVIEW

**Comment by SKR301** [comment]
Ah...that's my mistake.
I just selected all the files while uploading them.

**Comment by norkator** [comment]
Okay I deleted those binary class files

**Comment by norkator** [comment]
So whats the chance to get also decoding?

**Comment by SKR301** [comment]
Yeah, that's allright
Thanks

**Pull request merged**
