### PR TITLE
#45 ADFGVX cipher with keys implemented

### PR DESCRIPTION
**Pull request by SKR301**
#45  ADFGVX cipher with keys implemented
NOTE: Key size must be < 10!

### CODE REVIEW

**Comment by SKR301** [comment]
Updated the code for 2 keys as requested...
The Wiki link is not complete, it doesn't show how they generated Polybius square for the cipher.

Refactored the code according to [ADFGVX](https://www.boxentriq.com/code-breaking/adfgvx-cipher)

**Review by norkator — CHANGES_REQUESTED** [review]
Still not working. Gives wrong output.

**Comment by norkator** [comment]
Screenshot 2021-11-14 at 11 44 00

With same keys and input I cannot still see this output: `DGDD DAGD DGAF ADDF DADV DVFA ADVX`

**Comment by SKR301** [comment]
That's cause wikipedia example has WRONG polybius square.

**Comment by norkator** [comment]
> That's cause wikipedia example has INCORRECT polybius square.

😲 you should edit wikipedia page!

**Review by norkator — APPROVED** [review]

**Pull request merged**
